package xlsx

import (
	. "gopkg.in/check.v1"
)

type MacNumbersSuite struct{}

var _ = Suite(&MacNumbersSuite{})

// Test that we can successfully read an XLSX file generated by
// Numbers for Mac.
func (m *MacNumbersSuite) TestMacNumbers(c *C) {
	xlsxFile, err := OpenFile("macNumbersTest.xlsx")
	c.Assert(err, IsNil)
	c.Assert(xlsxFile, NotNil)
	sheet, ok := xlsxFile.Sheets["主动技能"]
	c.Assert(ok, Equals, true)
	s := sheet.Cell(0, 0).String()
	c.Assert(s, Equals, "编号")
}
