package xlsx

import (
	"testing"
)

// Test that we can successfully read an XLSX file generated by
// Numbers for Mac.
func TestMacNumbers(t *testing.T) {
	xlsxFile, error := OpenFile("MacNumbersTest.xlsx")
	if error != nil {
		t.Error(error.Error())
		return
	}
	if xlsxFile == nil {
		t.Error("OpenFile returned nil FileInterface without generating an os.Error")
		return
	}
	s := xlsxFile.Sheets[0].Cell(0, 0).String()
	if s != "编号" {
		t.Errorf("[TestMacExcel] xlsxFile.Sheets[0].Cell(0,0).String():'%s'", s)
		return
	}
}
